# Generated by Django 3.0.8 on 2020-08-15 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_date', models.DateField(default=1)),
                ('character', models.CharField(default=1, max_length=100)),
                ('age', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('job', models.CharField(default='None', max_length=100)),
                ('title', models.CharField(default='None', max_length=100)),
                ('hp', models.IntegerField(default=100)),
                ('strength', models.IntegerField(default=1)),
                ('vitality', models.IntegerField(default=1)),
                ('agility', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('challenge_body', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='status.Challenge_Body')),
                ('challenge_mind', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='status.Challenge_Mind')),
                ('challenge_skill', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='status.Challenge_Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
    ]
