# Generated by Django 3.0.8 on 2020-08-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('level', models.IntegerField()),
                ('job', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('hp', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('vitality', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('intelligence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
