# Generated by Django 3.0.8 on 2020-08-09 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='status.Challenge'),
        ),
    ]
