# Generated by Django 3.0.8 on 2020-08-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200805_1817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='status',
            name='age',
        ),
        migrations.AlterField(
            model_name='status',
            name='agility',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='status',
            name='hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='intelligence',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='status',
            name='job',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='status',
            name='strength',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='vitality',
            field=models.IntegerField(default=1),
        ),
    ]
