# Generated by Django 3.0.8 on 2020-08-09 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('User', '0002_auto_20200809_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='rewards',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='status.Reward'),
        ),
    ]
