# Generated by Django 3.0.8 on 2020-08-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200809_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='character',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
