# Generated by Django 3.0.8 on 2020-08-09 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.Inventory'),
        ),
    ]
